server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chulai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 200
      max-wait: 10000
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update #important! Don't change!
      use-new-id-generator-mappings: true
    show-sql: false
    open-in-view: false
  resources:
    chain:
      enabled: true
  data:
    rest:
      base-path: /api
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZZ
    default-property-inclusion: non_null

wechat:
  sessionHost: https://api.weixin.qq.com/sns/jscode2session
  secret:
  appid:
  grantType: authorization_code